version: '3'

services:
  postgres:
    image: postgres
    container_name: 'mobilis-postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    ports:
      - '3333:3333'
    depends_on:
      - postgres
    volumes:
      - '.:/usr/app'
    container_name: 'app-mobilis'
    command: yarn dev

volumes:
  postgres_data:
