module.exports = {
  up: queryInterface => {
    return queryInterface.bulkInsert(
      'sensors',
      [
        {
          sensor_id: '0xCF00002',
          name: 'Velocidades',
          description: 'Velocidades',
          type: 'Velocidades',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF10002',
          name: 'Hôdometro Parcial',
          description: 'Hôdometro Parcial',
          type: 'Hôdometro Parcial',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF20002',
          name: 'Referências',
          description: 'Referências',
          type: 'Referências',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF30002',
          name: 'Temperaturas',
          description: 'Temperaturas',
          type: 'Temperaturas',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF40002',
          name: 'Correntes e Tensões',
          description: 'Correntes e Tensões',
          type: 'Correntes e Tensões',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF50002',
          name: 'Vetorial',
          description: 'Vetorial',
          type: 'Vetorial',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF60002',
          name: 'Vetorial - Ganhos',
          description: 'Vetorial - Ganhos',
          type: 'Vetorial - Ganhos',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF70002',
          name: 'Vetorial - Ganhos 2',
          description: 'Vetorial - Ganhos 2',
          type: 'Vetorial - Ganhos 2',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF80002',
          name: 'Falha e Alarmes WEG',
          description: 'Falha e Alarmes WEG',
          type: 'Falha e Alarmes WEG',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186555F4',
          name: 'Tensão Total e SoC',
          description: 'Tensão Total e SoC',
          type: 'Tensão Total e SoC',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186655F4',
          name: 'Temperaturas',
          description: 'Temperaturas',
          type: 'Temperaturas',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186955F4',
          name: 'Max/Min Temperatura',
          description: 'Max/Min Temperatura',
          type: 'Max/Min Temperatura',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186A55F4',
          name: 'Tensões Extremas',
          description: 'Tensões Extremas',
          type: 'Tensões Extremas',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186B55F4',
          name: 'Tensões Células',
          description: 'Tensões Células',
          type: 'Tensões Células',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186C55F4',
          name: 'Temperatura Celulas',
          description: 'Temperatura Celulas',
          type: 'Temperatura Celulas',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186D55F4',
          name: 'Temperatura Celulas',
          description: 'Temperatura Celulas',
          type: 'Temperatura Celulas',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186E55F4',
          name: 'Temperatura Celulas',
          description: 'Temperatura Celulas',
          type: 'Temperatura Celulas',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x10F00001',
          name: 'Hôdometro Total',
          description: 'Hôdometro Total',
          type: 'Hôdometro Total',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x0CF30003',
          name: 'Carro Status',
          description: 'Carro Status',
          type: 'Carro Status',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x0CF40003',
          name: 'Temperatura Check',
          description: 'Temperatura Check',
          type: 'Temperatura Check',
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      {}
    );
  },

  down: queryInterface => {
    return queryInterface.bulkDelete('sensors', null, {});
  },
};
