module.exports = {
  up: queryInterface => {
    return queryInterface.bulkInsert(
      'word',
      [
        {
          sensor_id: '0xcf00002',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf00002',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf10002',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf10002',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf10002',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf20002',
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf30002',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf30002',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf30002',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf30002',
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf40002',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf40002',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf40002',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf40002',
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf50002',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf50002',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf50002',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf50002',
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf60002',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf60002',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf60002',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf60002',
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf70002',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf70002',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf70002',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf70002',
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf80002',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf80002',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186555f4',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186555f4',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186555f4',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186655f4',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186655f4',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186655f4',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186655f4',
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186955f4',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186955f4',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186a55f4',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186a55f4',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186a55f4',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186a55f4',
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186b55f4',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186b55f4',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186b55f4',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186b55f4',
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186c55f4',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186c55f4',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186c55f4',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186c55f4',
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186d55f4',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186d55f4',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186d55f4',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186d55f4',
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186e55f4',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186e55f4',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186e55f4',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186e55f4',
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x10f00001',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x10f00001',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x0cf30003',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x0cf30003',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x0cf40003',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x0cf40003',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      {}
    );
  },

  down: queryInterface => {
    return queryInterface.bulkDelete('word', null, {});
  },
};
