module.exports = {
  up: queryInterface => {
    return queryInterface.bulkInsert(
      'word',
      [
        {
          sensor_id: '0xCF00002',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF00002',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF10002',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF10002',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF10002',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF20002',
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF30002',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF30002',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF30002',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF30002',
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF40002',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF40002',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF40002',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF40002',
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF50002',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF50002',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF50002',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF50002',
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF60002',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF60002',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF60002',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF60002',
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF70002',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF70002',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF70002',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF70002',
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF80002',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xCF80002',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186555F4',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186555F4',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186555F4',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186655F4',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186655F4',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186655F4',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186655F4',
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186955F4',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186955F4',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186A55F4',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186A55F4',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186A55F4',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186A55F4',
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186B55F4',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186B55F4',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186B55F4',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186B55F4',
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186C55F4',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186C55F4',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186C55F4',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186C55F4',
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186D55F4',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186D55F4',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186D55F4',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186D55F4',
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186E55F4',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186E55F4',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186E55F4',
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186E55F4',
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x10F00001',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x10F00001',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x0CF30003',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x0CF30003',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x0CF40003',
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x0CF40003',
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      {}
    );
  },

  down: queryInterface => {
    return queryInterface.bulkDelete('word', null, {});
  },
};
