module.exports = {
  up: (queryInterface) => {
    return queryInterface.bulkInsert(
      'word',
      [
        {
          sensor_id: '0xcf00002',
          word: 1,
          name: 'Velocidade Km/h',
          alarm: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf00002',
          word: 2,
          name: 'Velocidade RPM',
          alarm: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf10002',
          name: '% Pedal Acelerador 1',
          alarm: false,
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf10002',
          name: '% Pedal Acelerador 2',
          alarm: false,
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf10002',
          name: 'Carga Bateria',
          alarm: false,
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf20002',
          name: 'Torque Motor',
          alarm: false,
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf30002',
          word: 1,
          name: 'Temperatura Mosfet 1',
          alarm: false,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf30002',
          name: 'Temperatura Mosfet 2',
          alarm: false,
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf30002',
          name: 'Temperatura Ambiente',
          alarm: false,
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf30002',
          name: 'Temperatura Motor',
          alarm: false,
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf40002',
          name: 'Corrente Regeneração Motor',
          alarm: false,
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf40002',
          name: 'Corrente Motor',
          alarm: false,
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf40002',
          name: 'Tensão Motor',
          alarm: false,
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf40002',
          name: 'Potência Motor',
          alarm: false,
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf50002',
          name: 'Alarme Atual',
          alarm: true,
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf50002',
          name: 'Falha Atual',
          alarm: true,
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf50002',
          name: 'Ultima Falha',
          alarm: true,
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf50002',
          name: 'Segunda Falha',
          alarm: true,
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf60002',
          name: 'Terceira Falha',
          alarm: true,
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf60002',
          name: 'Quarta Falha',
          alarm: true,
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf60002',
          name: 'Quinta Falha',
          alarm: true,
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf60002',
          name: 'Corrente da Ultima Falha',
          alarm: true,
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf70002',
          name: 'Tensão Bateria Ultima Falha',
          alarm: true,
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf70002',
          name: 'Rotação Ultima Falha (rpm)',
          alarm: true,
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf70002',
          name: 'Frequência Ultima Falha',
          alarm: true,
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf70002',
          name: 'Tensão Motor Ultima Falha',
          alarm: true,
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf80002',
          name: 'Corrente de Entrada do Inversor',
          alarm: false,
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0xcf80002',
          name: 'Código de Alarme CVW300',
          alarm: true,
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186555f4',
          name: 'Tensão Total',
          alarm: false,
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186555f4',
          name: 'Corrente de Carga Total',
          alarm: false,
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186555f4',
          name: 'Corrente de Descarga',
          alarm: false,
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186655f4',
          name: 'Temperatura Bateria Ponto 1',
          alarm: false,
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186655f4',
          name: 'Temperatura Bateria Ponto 2',
          alarm: false,
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186655f4',
          name: 'Temperatura Bateria Ponto 3',
          alarm: false,
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186655f4',
          name: 'Temperatura Bateria Ponto 4',
          alarm: false,
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186955f4',
          name: 'Máxima Temperatura',
          alarm: false,
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186955f4',
          name: 'Minima Temperatura',
          alarm: false,
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186a55f4',
          name: 'Tensão Mais Alta',
          alarm: false,
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186a55f4',
          name: 'Tensão Mais Baixa',
          alarm: false,
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186a55f4',
          name: 'ID da Célula de Maior Tensão',
          alarm: false,
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186a55f4',
          name: 'ID da Célula de Menor Tensão',
          alarm: false,
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186b55f4',
          name: 'Temperatura Célula 1',
          alarm: false,
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186b55f4',
          name: 'Temperatura Célula 2',
          alarm: false,
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186b55f4',
          name: 'Temperatura Célula 3',
          alarm: false,
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186b55f4',
          name: 'Temperatura Célula 4',
          alarm: false,
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186c55f4',
          name: 'Temperatura Célula 5',
          alarm: false,
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186c55f4',
          name: 'Temperatura Célula 6',
          alarm: false,
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186c55f4',
          name: 'Temperatura Célula 7',
          alarm: false,
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186c55f4',
          name: 'Temperatura Célula 8',
          alarm: false,
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186d55f4',
          name: 'Temperatura Célula 9',
          alarm: false,
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186d55f4',
          name: 'Temperatura Célula 10',
          alarm: false,
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186d55f4',
          name: 'Temperatura Célula 11',
          alarm: false,
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186d55f4',
          name: 'Temperatura Célula 12',
          alarm: false,
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186e55f4',
          name: 'Temperatura Célula 13',
          alarm: false,
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186e55f4',
          name: 'Temperatura Célula 14',
          alarm: false,
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186e55f4',
          name: 'Temperatura Célula 15',
          alarm: false,
          word: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x186e55f4',
          name: 'Temperatura Célula 16',
          alarm: false,
          word: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x10f00001',
          name: 'Hodômetro Total',
          alarm: false,
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x10f00001',
          name: 'Horimetro Total',
          alarm: false,
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x0cf30003',
          name: 'Carro Ligado',
          alarm: false,
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x0cf30003',
          name: 'Carro Desligado',
          alarm: false,
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x0cf40003',
          name: 'Temperatura Inversor',
          alarm: false,
          word: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          sensor_id: '0x0cf40003',
          name: 'Temperatura Bateria Média',
          alarm: false,
          word: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      {}
    );
  },

  down: (queryInterface) => {
    return queryInterface.bulkDelete('word', null, {});
  },
};
